const Counties = [
  { id: 3, name: "", deliver: 0 },
  { id: 1, name: "Nairobi", deliver: 150 },
  { id: 2, name: "Kiambu", deliver: 100 },
];

const locations = [
  { id: 193, name: " " },
  { id: 1, name: "Banana Hill" },
  { id: 2, name: "Bibirioni" },
  { id: 3, name: "Cianda" },
  { id: 4, name: "Dagoretti" },
  { id: 5, name: "Delta" },
  { id: 6, name: "Gachagi" },
  { id: 7, name: "Gachika" },
  { id: 8, name: "Gachororo" },
  { id: 9, name: "Gachie" },
  { id: 10, name: "Gaitu" },
  { id: 11, name: "Gathanga" },
  { id: 12, name: "Gathiruini" },
  { id: 13, name: "Gatong'ora" },
  { id: 14, name: "Gatukuyu" },
  { id: 15, name: "Gatundu" },
  { id: 16, name: "Gatura" },
  { id: 17, name: "Gichuru" },
  { id: 18, name: "Gikambura" },
  { id: 19, name: "Gikoe" },
  { id: 20, name: "Gikono" },
  { id: 21, name: "Githunguri" },
  { id: 22, name: "Githurai" },
  { id: 23, name: "Gituamba" },
  { id: 24, name: "Gitweko" },
  { id: 25, name: "Ichaweri" },
  { id: 26, name: "Ikinu" },
  { id: 27, name: "Imara Daima" },
  { id: 28, name: "Juja" },
  { id: 29, name: "Kahuho" },
  { id: 30, name: "Kahawa" },
  { id: 31, name: "Kahawa Sukari" },
  { id: 32, name: "Kahawa Wendani" },
  { id: 33, name: "Kabete" },
  { id: 34, name: "Kabuku" },
  { id: 35, name: "Kambaa" },
  { id: 36, name: "Kamiti" },
  { id: 37, name: "Kamwangi" },
  { id: 38, name: "Kangoya" },
  { id: 39, name: "Kangundo" },
  { id: 40, name: "Kanunga" },
  { id: 41, name: "Karai" },
  { id: 42, name: "Karatu" },
  { id: 43, name: "Karuri" },
  { id: 44, name: "Kiamaina" },
  { id: 45, name: "Kiamariga" },
  { id: 46, name: "Kiamumbi" },
  { id: 47, name: "Kiamwangi" },
  { id: 48, name: "Kiandutu" },
  { id: 49, name: "Kiang'ombe" },
  { id: 50, name: "Kianjau" },
  { id: 51, name: "Kibichoi" },
  { id: 52, name: "Kibiko" },
  { id: 53, name: "Kibunja" },
  { id: 54, name: "Kigumo" },
  { id: 55, name: "Kigumo Gakuyu" },
  { id: 56, name: "Kigwe" },
  { id: 57, name: "Kihara" },
  { id: 58, name: "Kihingo" },
  { id: 59, name: "Kikuyu" },
  { id: 60, name: "Kilimambogo" },
  { id: 61, name: "Kinale" },
  { id: 62, name: "Kindaruma" },
  { id: 63, name: "Kinoo" },
  { id: 64, name: "Kinungi" },
  { id: 65, name: "Kiratina" },
  { id: 66, name: "Kiria-ini" },
  { id: 67, name: "Kiriita" },
  { id: 68, name: "Kiriko" },
  { id: 69, name: "Kirigiti" },
  { id: 70, name: "Kiriti Murungai" },
  { id: 71, name: "Kiwara" },
  { id: 72, name: "Kongo" },
  { id: 73, name: "Kwa Maiko" },
  { id: 74, name: "Kwamaiko" },
  { id: 75, name: "Kyuna" },
  { id: 76, name: "Lari" },
  { id: 77, name: "Limuru" },
  { id: 78, name: "Maai Mahiu" },
  { id: 79, name: "Magumu" },
  { id: 80, name: "Makongeni" },
  { id: 81, name: "Mang'u" },
  { id: 82, name: "Mathare" },
  { id: 83, name: "Mawingu" },
  { id: 84, name: "Mbiri" },
  { id: 85, name: "Miguta" },
  { id: 86, name: "Mihango" },
  { id: 87, name: "Mikinduri" },
  { id: 88, name: "Mwiki" },
  { id: 89, name: "Nachu" },
  { id: 90, name: "Ndeiya" },
  { id: 91, name: "Ndumberi" },
  { id: 92, name: "Ngara" },
  { id: 93, name: "Ngenda" },
  { id: 94, name: "Ngewa" },
  { id: 95, name: "Ngoliba" },
  { id: 96, name: "Ngong" },
  { id: 97, name: "Ngecha" },
  { id: 98, name: "Ngegu" },
  { id: 99, name: "Nyadhuna" },
  { id: 100, name: "Nyathuna" },
  { id: 101, name: "Nyokabi" },
  { id: 102, name: "Pongola" },
  { id: 103, name: "Rironi" },
  { id: 104, name: "Ruaka" },
  { id: 105, name: "Rugongo" },
  { id: 106, name: "Ruiru" },
  { id: 107, name: "Runyenjes" },
  { id: 108, name: "Thathi" },
  { id: 109, name: "Thika" },
  { id: 110, name: "Tigoni" },
  { id: 111, name: "Ting'ang'a" },
  { id: 112, name: "Uplands" },
  { id: 113, name: "Wangige" },
  { id: 114, name: "Wanguru" },
  { id: 115, name: "Airbase" },
  { id: 116, name: "Bahati" },
  { id: 117, name: "Baba Dogo" },
  { id: 118, name: "Bellevue" },
  { id: 119, name: "Buru Buru" },
  { id: 120, name: "City Square" },
  { id: 121, name: "Civil Servants" },
  { id: 122, name: "Dandora" },
  { id: 123, name: "Donholm" },
  { id: 124, name: "Eastleigh" },
  { id: 125, name: "EMBAKASI" },
  { id: 126, name: "Fedha" },
  { id: 127, name: "Gikomba" },
  { id: 128, name: "Githurai" },
  { id: 129, name: "Highridge" },
  { id: 130, name: "Hospital" },
  { id: 131, name: "Huruma" },
  { id: 132, name: "Imara Daima" },
  { id: 133, name: "Industrial Area" },
  { id: 134, name: "Jericho" },
  { id: 135, name: "Jogoo Road" },
  { id: 136, name: "Kabiria" },
  { id: 137, name: "Kahawa West" },
  { id: 138, name: "Kaloleni" },
  { id: 139, name: "Kangemi" },
  { id: 140, name: "Karen" },
  { id: 141, name: "Karura" },
  { id: 142, name: "Kawangware" },
  { id: 143, name: "Kibera" },
  { id: 144, name: "Kileleshwa" },
  { id: 145, name: "Kilimani" },
  { id: 146, name: "Kimathi" },
  { id: 147, name: "Kitisuru" },
  { id: 148, name: "KNH" },
  { id: 149, name: "Koibatek" },
  { id: 150, name: "Komarock" },
  { id: 151, name: "KU" },
  { id: 152, name: "Kware" },
  { id: 153, name: "Kyangombe" },
  { id: 154, name: "Lang'ata" },
  { id: 155, name: "Lavington" },
  { id: 156, name: "Loresho" },
  { id: 157, name: "Lucky Summer" },
  { id: 158, name: "Madaraka" },
  { id: 159, name: "Majengo" },
  { id: 160, name: "Makadara" },
  { id: 161, name: "Makongeni" },
  { id: 162, name: "Mathare North" },
  { id: 163, name: "Mathare Valley" },
  { id: 164, name: "Maziwa" },
  { id: 165, name: "Mbotela" },
  { id: 166, name: "Mwiki" },
  { id: 167, name: "Nairobi Central" },
  { id: 168, name: "Nairobi West" },
  { id: 169, name: "Ngara" },
  { id: 170, name: "Njiru" },
  { id: 171, name: "Ongata Rongai" },
  { id: 172, name: "Pangani" },
  { id: 173, name: "Parklands" },
  { id: 174, name: "Pipeline" },
  { id: 175, name: "Pumwani" },
  { id: 176, name: "Riruta" },
  { id: 177, name: "Ruaraka" },
  { id: 178, name: "Saika" },
  { id: 179, name: "South B" },
  { id: 180, name: "South C" },
  { id: 181, name: "Soweto" },
  { id: 182, name: "Starehe" },
  { id: 183, name: "Sunton" },
  { id: 184, name: "Tassia" },
  { id: 185, name: "Thome" },
  { id: 186, name: "Umoja" },
  { id: 187, name: "Upper Hill" },
  { id: 188, name: "Utawala" },
  { id: 189, name: "Valley Road" },
  { id: 190, name: "Viwandani" },
  { id: 191, name: "Westlands" },
  { id: 192, name: "Woodley" },
];

const subCounties = [
  { id: 29, name: " " },
  { id: 1, name: "Ruaraka" },
  { id: 2, name: "Embakasi" },
  { id: 3, name: "Embakasi North" },
  { id: 4, name: "Embakasi Central" },
  { id: 5, name: "Embakasi East" },
  { id: 6, name: "Embakasi West" },
  { id: 7, name: "Starehe" },
  { id: 8, name: "Dagoretti North" },
  { id: 9, name: "Dagoretti South" },
  { id: 10, name: "Langata" },
  { id: 11, name: "Kibra" },
  { id: 12, name: "Roysambu" },
  { id: 13, name: "Kasarani" },
  { id: 14, name: "Westlands" },
  { id: 15, name: "Makadara" },
  { id: 16, name: "Mathare" },
  { id: 17, name: "Limuru" },
  { id: 18, name: "Kikuyu" },
  { id: 19, name: "Kabete" },
  { id: 20, name: "Lari" },
  { id: 21, name: "Gatundu South" },
  { id: 22, name: "Gatundu North" },
  { id: 23, name: "Kiambu" },
  { id: 24, name: "Ruiru" },
  { id: 25, name: "Kiambaa" },
  { id: 26, name: "Juja" },
  { id: 27, name: "Thika Town" },
  { id: 28, name: "Githunguri" },
];


const month = [
   { id: 1, name: "JAN" },
  { id: 2, name: "FEB" },
  { id: 3, name: "MAR" },
  { id: 4, name: "APR" },
  { id: 5, name: "MAY" },
  { id: 6, name: "JUNE" },
  { id: 7, name: "JULY" },
  { id: 8, name: "AUG" },
  { id: 9, name: "SEPT" },
  { id: 10, name: "OCT" },
  { id: 11, name: "NOV" },
  { id: 12, name: "DEC" }]

export {subCounties,locations,Counties,month}